/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chaintransfer_native__ChaintransferClient */

#ifndef _Included_com_chaintransfer_native__ChaintransferClient
#define _Included_com_chaintransfer_native__ChaintransferClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chaintransfer_native__ChaintransferClient
 * Method:    chaintransfer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_chaintransfer_native_1_ChaintransferClient_chaintransfer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
