quarkus.http.access-log.enabled=true
quarkus.http.http2=true

quarkus.native.additional-build-args=--initialize-at-run-time=com.chaintransfer.native_.ChaintransferClient,-Djava.library.path=./jni
quarkus.jvm.additional-args=-Djava.library.path=./jni
quarkus.package.output=chaintransfer-web