on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: container-registry.oracle.com/graalvm/native-image:25
    steps:
      - uses: actions/checkout@v4
      - run: apt-get update && apt-get install -y g++
      - run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.package.jar.enabled=false
